spring:
  datasource:
    url: jdbc:mysql://mysql:3306/veiculos
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8081